apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta-sprayer
  labels:
    app: beta-sprayer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beta-sprayer
  template:
    metadata:
      labels:
        app: beta-sprayer
    spec:
      containers:
      - name: beta-sprayer
        image: bliu23/beta-sprayer-2:0.0.0
        ports:
        - containerPort: 8000
